spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  liquibase:
    enabled: true
    change-log: db.changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/zoo?currentSchema=public
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
server:
  port: 8080